name: Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get version from commit
        id: get_version
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          if echo "$COMMIT_MSG" | grep -q "^BREAKING CHANGE:" || echo "$COMMIT_MSG" | grep -q "!:"; then
            echo "bump=major" >> $GITHUB_OUTPUT
          elif echo "$COMMIT_MSG" | grep -q "^feat:"; then
            echo "bump=minor" >> $GITHUB_OUTPUT
          elif echo "$COMMIT_MSG" | grep -q "^fix:"; then
            echo "bump=patch" >> $GITHUB_OUTPUT
          else
            echo "bump=none" >> $GITHUB_OUTPUT
          fi

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ steps.get_version.outputs.bump }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: steps.tag_version.outputs.new_tag
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          draft: false
          prerelease: false

      - name: Set up Python
        if: steps.tag_version.outputs.new_tag
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        if: steps.tag_version.outputs.new_tag
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Configure Poetry
        if: steps.tag_version.outputs.new_tag
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

      - name: Update version in pyproject.toml
        if: steps.tag_version.outputs.new_tag
        run: |
          poetry version ${GITHUB_REF#refs/tags/v}

      - name: Build and publish
        if: steps.tag_version.outputs.new_tag
        run: |
          poetry build
          poetry publish
